import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "./Navbar";
import { Suspense } from "react";
import AuthProvider from "./auth/provider";
import Script from "next/script";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  weight: ["400", "500"],
  subsets: ["latin"],
  display: "swap",
});

const poppins = localFont({
  src: "../public/fonts/Poppins-Regular.woff2",
  variable: "--font-poppins", // this is just a name of the custom css variable or property that represents our font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "XXXXXXXXXXXXXXXXXX",
    siteName: "Next.js",
    images: [
      {
        url: "XXXXXXXXXXXXXXXXXXXXXXXXX",
        width: 800,
        height: 600,
      },
      {
        url: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        width: 900,
        height: 800,
        alt: "My new app",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
      {/* <body className={roboto.className}>  You can also do this*/}
      <body className={poppins.variable}>
        <AuthProvider>
          <Navbar />
          <p className={poppins.className}>Sample font</p>
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
